### ISSUE TITLE
SurefireForksConfigurationTest is failing on master

### ISSUE THREAD

**Issue by dipak-pawar** [arquillian/smart-testing#275]
*Steps To Reproduce*
* mvn clean install -DskipTests=true
* Run any test from `SurefireForksConfigurationTest`

Looks like `affected` strategy is not working as per expectation.

Travis is failing - https://travis-ci.org/arquillian/smart-testing/builds/308534204

**Comment by bartoszmajsak** [comment]
The issue was a wrong commit message taken from my obsolete [dogfood repo](https://github.com/arquillian/smart-testing-dogfood-repo) which I thought is up-to-date when fixing problem @lordofthejars was facing with his new tests for affected/annotations.

Faulty commit description:

```
tag affected_02
Tagger: Bartosz Majsak <bartosz.majsak@gmail.com>
Date:   Thu Jul 13 07:10:53 2017 +0200

Inlined variable in a method

commit 814dfb5512046f86a7ec14dcab3baabacb8f1107
Author: Bartosz Majsak <bartosz.majsak@gmail.com>
Date:   Tue Jul 4 10:24:50 2017 +0200

    affected: inlined variable in ConfigurationSysPropResolver#resolveSystemProperties
    
    + org.jboss.arquillian.config.impl.extension.ArquillianDescriptorPropertiesTestCase
```

Expected commit description:

```
tag affected_02
Tagger: Matous Jobanek <mjobanek@redhat.com>
Date:   Fri Aug 11 09:49:18 2017 +0200

Inlined variable in a method

commit 49667856365106bffc56a0f3aa542e73cc2c14e5
Author: Bartosz Majsak <bartosz.majsak@gmail.com>
Date:   Tue Jul 4 10:24:50 2017 +0200

    affected: inlined variable in ConfigurationSysPropResolver#resolveSystemProperties
    
    + org.jboss.arquillian.config.impl.extension.ArquillianDescriptorPropertiesTestCase
    + org.jboss.arquillian.config.impl.extension.ConfigurationRegistrarTestCase
    + org.jboss.arquillian.config.impl.extension.SyspropReplacementInArqXmlTestCase
```

as you can see it has 2 tests expected to be executed.

Two key takeaways from it:

- instead of pushing all the things with `--force` delete faulty tags (both locally and upstream) and push again - limits the risk of unwanted side-effects
- run the build against it locally before firing updates in dogfood repo

Additionally, we should rethink if the way of defining test expectations with tags is something we are comfortable with.
