### ISSUE TITLE
Include / exclude refactoring

### ISSUE THREAD

**Issue by bartoszmajsak** [arquillian/smart-testing#8]
We have to review and refactor usage of `globPatterns` - it's strange that we keep both exclusions and inclusions in [one place](https://github.com/arquillian/smart-testing/blob/6bac712e6822898a8cca6ca76e2ea567bc115496/surefire-provider/src/main/java/org/arquillian/smart/testing/surefire/provider/TestStrategyApplier.java#L78), but also that we pass `globPatterns` around when creating / loading test execution strategies.

**Comment by MatousJobanek** [comment]
Instead of using include/exclude, the Planner implementations could take a list of test classes that should be run. This list [is retrieved ](https://github.com/arquillian/smart-testing/blob/master/surefire-provider/src/main/java/org/arquillian/smart/testing/surefire/provider/SmartTestingSurefireProvider.java#L29) from an original Surefire provider, so it takes into account also the includes/excludes.
Currently, this list is used only for [checking](https://github.com/arquillian/smart-testing/blob/master/surefire-provider/src/main/java/org/arquillian/smart/testing/surefire/provider/TestStrategyApplier.java#L81) whether all returned test classes are intended to run. 
As a benefit would be that the planner can limit its logic only for specified test classes - not for all files that match the regex.

**Comment by bartoszmajsak** [comment]
Closed through several refactoring rounds #109
